[package]
name = "rg3d-core"
version = "0.14.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Shared core for rg3d engine and its external crates."
repository = "https://github.com/mrDIMAS/rg3d"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
readme = "README.md"

[dependencies]
rg3d-core-derive = { path = "../rg3d-core-derive", version = "0.10.0" }

base64 = "0.13.0"
byteorder = "1.4.2"
rand = "0.8.3"
memoffset = "0.6.1"
lazy_static = "1.4.0"
nalgebra = "0.26.2"
arrayvec = "0.7.0"
futures = {version = "0.3.13", features = ["thread-pool"] }
uuid = { version = "0.8.2", features = ["v4","wasm-bindgen"] }
instant = {version = "0.1.9", features = ["wasm-bindgen"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.50", features = ["Request", "Window", "Response", "AudioContext", "AudioBuffer", "AudioContextOptions", "AudioNode", "AudioBufferSourceNode", "AudioDestinationNode"] }
wasm-bindgen = "0.2.73"
wasm-bindgen-futures = "0.4.23"
js-sys = "0.3.50"

[features]
enable_profiler = []