[package]
name = "rg3d"
version = "0.1.1"
authors = ["mrDIMAS <d1maxa@yandex.ru>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
glutin = "0.21.0"
image = "0.22.1"
lexical = "3.0.0"
byteorder = "1.3.2"
base64 = "0.10.1"
inflate = "0.4.5"