[package]
name = "rg3d-core"
version = "0.1.0"
authors = ["Dmitry <d1maxa@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.10.1"
byteorder = "1.3.2"
rand = "0.7.0"