[package]
name = "rg3d-sound"
version = "0.1.0"
authors = ["Dmitry <d1maxa@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rg3d-core = { path = "../rg3d-core" }
byteorder = "1.3.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = {version = "0.3.8", features = ["minwindef", "winnt", "windef", "winuser", "dsound", "synchapi", "winbase" ] }

