[package]
name = "rg3d-sound"
version = "0.6.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Sound library for games."
keywords = ["sound", "game", "hrtf", "binaural", "reverb"]
repository = "https://github.com/mrDIMAS/rg3d-sound"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md", "/examples/*"]

[dependencies]
rg3d-core = { path = "../rg3d-core", version = "0.2.4" }
byteorder = "1.3.2"
rustfft = "3.0.0"
lewton = "0.9.4"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = {version = "0.3.8", features = ["minwindef", "winnt", "windef", "winuser", "dsound", "synchapi", "winbase" ] }

[target.'cfg(target_os = "linux")'.dependencies]
alsa-sys = { version = "0.2.0" }
