[package]
name = "rg3d"
version = "0.3.1"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "3D Game engine"
keywords = ["sound", "game", "engine", "3d", "gui"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
repository = "https://github.com/mrDIMAS/rg3d"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rg3d-core="0.1.9"
rg3d-sound="0.2.0"
rg3d-physics="0.1.7"
glutin = "0.22.0-alpha3"
image = "0.22.1"
lexical = "3.0.0"
byteorder = "1.3.2"
inflate = "0.4.5"
rand = "0.7.0"
lazy_static = "1.4.0"