[package]
name = "rg3d-core"
version = "0.2.1"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Shared core for rg3d engine and its external crates."
repository = "https://github.com/mrDIMAS/rg3d-core"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]

[dependencies]
base64 = "0.10.1"
byteorder = "1.3.2"
rand = "0.7.0"