[package]
name = "rg3d"
version = "0.19.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "3D Game engine"
keywords = ["sound", "game", "engine", "3d", "gui"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
repository = "https://github.com/mrDIMAS/rg3d"
readme = "README.md"

[workspace]
members = ["rg3d-core", "rg3d-sound", "rg3d-ui", "examples/wasm"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rg3d-core = { path = "rg3d-core", version = "0.14.0" }
rg3d-sound = { path = "rg3d-sound", version = "0.21.0" }
rg3d-ui = { path = "rg3d-ui", version = "0.10.0" }
image = { version = "0.23.12", default-features = false, features = ["gif", "jpeg", "png", "tga", "tiff", "bmp"] }
lexical = "5.2.0"
inflate = "0.4.5"
serde = { version = "^1.0.0", features = ["derive"], optional = true }
lazy_static = "1.4.0"
ddsfile = "0.4.0"
rapier3d = {version = "0.7" }
rayon = "1.5.0"
tbc = "0.3.0"
# Temporary, until https://github.com/grovesNL/glow/pull/157 is merged and new glow (0.10?) published on crates.io
glow = { git = "https://github.com/mrDIMAS/glow", branch = "main" }

[dev-dependencies]
imageproc = "0.21.0"

[features]
enable_profiler = ["rg3d-core/enable_profiler"]
serde_integration = ["glutin/serde", "serde"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.26.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.24.0", features=["web-sys"] }


