[package]
name = "rg3d"
version = "0.20.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "3D Game engine"
keywords = ["sound", "game", "engine", "3d", "gui"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
repository = "https://github.com/mrDIMAS/rg3d"
readme = "README.md"

[workspace]
members = ["rg3d-core-derive", "rg3d-core", "rg3d-sound", "rg3d-ui", "examples/wasm"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rg3d-core = { path = "rg3d-core", version = "0.15.0" }
rg3d-sound = { path = "rg3d-sound", version = "0.22.0" }
rg3d-ui = { path = "rg3d-ui", version = "0.11.0" }
image = { version = "0.23", default-features = false, features = ["gif", "jpeg", "png", "tga", "tiff", "bmp"] }
lexical = "5.2.0"
inflate = "0.4.5"
serde = { version = "^1.0.0", features = ["derive"], optional = true }
lazy_static = "1.4.0"
ddsfile = "0.4.0"
rapier3d = {version = "0.9" }
rapier2d = {version = "0.9" }
rayon = "1.5.0"
tbc = "0.3.0"
bitflags = "1.2.1"
glow = "0.10"
walkdir = "2"

[dev-dependencies]
imageproc = "0.22.0"

[features]
enable_profiler = ["rg3d-core/enable_profiler"]
serde_integration = ["glutin/serde", "serde"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.27.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.25.0", features=["web-sys"] }


