[package]
name = "rg3d-sound"
version = "0.1.1"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Sound library for games."
keywords = ["sound", "game"]
repository = "https://github.com/mrDIMAS/rg3d-sound"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md", "/examples/*"]

[dependencies]
rg3d-core = { path = "../rg3d-core" }
byteorder = "1.3.2"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = {version = "0.3.8", features = ["minwindef", "winnt", "windef", "winuser", "dsound", "synchapi", "winbase" ] }