[package]
name = "rg3d-physics"
version = "0.7.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Physics library for rg3d-engine."
keywords = ["physics", "game"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
readme = "README.md"

[dependencies]
rg3d-core = { path = "../rg3d-core", version = "0.9.0" }
bitflags = "1.2.1"

[features]
enable_profiler = ["rg3d-core/enable_profiler"]