[package]
name = "rg3d-ui"
version = "0.3.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "Extendable UI library"
keywords = ["ui", "game", "gui"]
repository = "https://github.com/mrDIMAS/rg3d-ui"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]

[dependencies]
rg3d-core = { path = "../rg3d-core", version = "0.5.0" }
lazy_static = "1.4.0"