[package]
name = "rg3d"
version = "0.5.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"
license = "MIT"
description = "3D Game engine"
keywords = ["sound", "game", "engine", "3d", "gui"]
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]
repository = "https://github.com/mrDIMAS/rg3d"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
rg3d-core = { path = "../rg3d-core", version = "0.2.1" }
rg3d-sound = { path = "../rg3d-sound", version = "0.2.2" }
rg3d-physics = { path = "../rg3d-physics", version = "0.2.0" }
glutin = "0.22.0-alpha5"
image = "0.22.1"
lexical = "3.0.0"
byteorder = "1.3.2"
inflate = "0.4.5"
rand = "0.7.0"
lazy_static = "1.4.0"