[package]
name = "rusty-editor"
version = "0.4.0"
authors = ["Dmitry Stepanov <d1maxa@yandex.ru>"]
edition = "2018"

[dependencies]
rg3d = { version = "0.14.0", path = "../rg3d" }
lazy_static = "1.4.0"

[features]
enable_profiler = ["rg3d/enable_profiler"]