[package]
name = "rg3d"
version = "0.1.1"
authors = ["mrDIMAS <d1maxa@yandex.ru>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
glutin = "*"
image = "*"
lexical = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
byteorder = "*"
base64="*"