[package]
name = "wasm"
version = "0.1.0"
authors = ["Dmitry <d1maxa@yandex.ru>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rg3d = { path = "../../" }
wasm-bindgen = "0.2.73"